require("prototypes.battery-mk3-equipment")
require("prototypes.energy-shield-mk3-equipment")
require("prototypes.exoskeleton-mk2-equipment")
require("prototypes.fusion-reactor-mk3-equipment")
require("prototypes.personal-roboport-mk3-equipment")
require("prototypes.power-armor-mk3")